version: 4.0.0
variant: default
logo: /img/logo.svg
head:
    favicon: /img/favicon.svg
    open_graph:
        title: 
        type: 
        url: 
        image: 
        site_name: 
        author: 
        description: 
        twitter_card: 
        twitter_id: 
        twitter_site: 
        google_plus: 
        fb_admins: 
        fb_app_id: 
    structured_data:
        title: 
        description: 
        url: 
        author: 
        image: 
    meta:
        - ''
    rss: /atom.xml
navbar:
    menu:
        主页: /
        归档: /archives
        分类: /categories
        标签: /tags
        友链: /friends
        关于: /about
    links:
        GitHub:
            icon: fab fa-github
            url: 'https://github.com/zeinber'
# footer:
#     links:
#         Creative Commons:
#             icon: fab fa-creative-commons
#             url: 'https://creativecommons.org/'
#         Attribution 4.0 International:
#             icon: fab fa-creative-commons-by
#             url: 'https://creativecommons.org/licenses/by/4.0/'
#         NonCommercial:
#             icon: fab fa-creative-commons-nc
#             url: 'https://creativecommons.org/licenses/by-nc-sa/4.0/deed.en'
#         ShareAlike:
#             icon: fab fa-creative-commons-sa
#             url: 'https://creativecommons.org/licenses/by-nc-sa/4.0/deed.en'
article:
    highlight:
        theme: atom-one-light
        clipboard: true
        fold: unfolded
    # thumbnail: true
    readtime: true
    licenses:
        Creative Commons:
            icon: fab fa-creative-commons
            url: 'https://creativecommons.org/'
        'CC BY-NC-SA 4.0': 'https://creativecommons.org/licenses/by-nc-sa/4.0/'
search:
    type: insight
# comment:
#     type: gitalk
#     client_id: 8687afbf31f0041f005d
#     client_secret: 9949b2971fa855443467af73220daa9e8c0612fd
#     repo: ElaBosak233.github.io
#     owner: ElaBosak233
#     admin:
#         - ElaBosak233
# donates:
#     -
#         type: alipay
#         qrcode: /img/alipay.png
#     -
#         type: afdian
#         url: 'https://afdian.net/@ElaBosak233'
#     -
#         type: buymeacoffee
#         url: 'https://www.buymeacoffee.com/ElaBosak233'
    # -
    #     type: wechat
    #     qrcode: ''
share:
    type: sharethis
    install_url: 'https://platform-api.sharethis.com/js/sharethis.js#property=5ebf74e940b52d00198b513b&product=inline-share-buttons&cms=sop'
sidebar:
    left:
        sticky: true
    right:
        sticky: true
widgets:
    -
        position: left
        type: profile
        author: zeiber
        author_title: 打工人打工魂打工都是人上人
        location: 'HangZhou, China'
        avatar: /img/avatar.png
        avatar_rounded: true
        gravatar: 
        follow_link: 'https://github.com/zeinber'
    -
        position: left
        type: toc
    -
        position: left
        type: links
        links:
            fiteen: 'https://blog.fiteen.top'
    -
        position: left
        type: categories
    -
        position: right
        type: recent_posts
    -
        position: right
        type: archives
    -
        position: left
        type: tags
    -
        position: right
        type: subscribe_email
        description: 
        feedburner_id: ElaBosak233
    # - 
    #     position: right
    #     type: adsense
    #     client-id: ca-pub-5501586061537610
    #     slot_id: 
plugins:
    animejs: true
    back_to_top: true
    baidu_analytics:
        tracking_id: 
    busuanzi: false
    cnzz:
        id: 
        web_id: 
    gallery: true
    google_analytics:
        tracking_id: 
    hotjar:
        site_id: 
    katex: true
    mathjax: false
    outdated_browser: true
    progressbar: true
providers:
    cdn: unpkg
    fontcdn: loli
    iconcdn: loli